services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: carbot
      POSTGRES_PASSWORD: password
      POSTGRES_DB: carbot
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./database/models.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - bot-network
    ports:
      - "5432:5432"

  # # Опционально: nginx для продакшена
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - bot
  #   restart: unless-stopped
  #   networks:
  #     - bot-network
  #   profiles:
  #     - production

volumes:
  pg_data:

networks:
  bot-network:
    driver: bridge
